version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/hello_world_nodejs
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  InstallDep:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
