#!/bin/bash
cd /home/ubuntu/hello_world_nodejs
#curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
rm -rf node_modules
npm install --unsafe-perm
declare -A osInfo;
osInfo[/etc/redhat-release]=yum
osInfo[/etc/arch-release]=pacman
osInfo[/etc/gentoo-release]=emerge
osInfo[/etc/SuSE-release]=zypp
osInfo[/etc/debian_version]=apt-get

for f in ${!osInfo[@]}
do
   if [[ -f $f ]];then
       echo Package manager: ${osInfo[$f]}
          ${osInfo[$f]} install -y nodejs
   fi
done
npm install pm2 -g --unsafe-perm=true --allow-root
